model:
  num_blocks: 2
  hidden_groups: [256,512,512,512]
  strides: [2,2,2,1]
  down_blocks: ['ResNet', 'ResNet', 'ResNet', 'ResNet']
  up_blocks: ['ResNet', 'ResNet', 'ResNet', 'ResNet']
denoise:
  T_max: 1000
  timesteps: 250

train:
  bs: 2
  lr: 0.0005
  steps: 5000
  acc_steps: 32
  warmup: 0
  num_workers: -1
  save_every: 4000
  ckpt: "checkpoints/unet.ckpt"